version: '2'
services:
  nginx:
    image: certaincy/intranginx
    links:
      - web:web
      - api:api
    ports:
      - "80:80"
    env_file: production.env
  web:
    image: certaincy/intraweb
    ports:
      - "5000:80"
  api:
    image: certaincy/intraapi
    ports:
      - "3000:80"
    env_file: production.env
