version: '2'
services:
  nginx:
    build: ./nginx
    image: nginx:tag
    links:
      - web:web
      - api:api
    ports:
      - "80:80"
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: web:tag
    ports:
      - "5000:80"
    volumes:
      - .:/app
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: api:tag
    ports:
      - "3000:80"
    volumes:
      - .:/app
